apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloservice
  annotations: 
    litmuschaos.io/gitops: true
    litmuschaos.io/workflow: af0866dd-6a28-428b-9212-8c911d5db370
spec:
  selector:
    matchLabels:
      app: helloservice
  template:
    metadata:
      labels:
        app: helloservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saiyam911/test-k8s-app:sha-877a48d
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloservice
spec:
  type: ClusterIP
  selector:
    app: helloservice
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer

